apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: istio-demo
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /marketplace
        backend:
          serviceName: marketplace
          servicePort: 3000