apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: shipper-default
  namespace: istio-demo
spec:
  destination:
    name: shipper
  precedence: 1
  route:
  - labels:
      version: v1