apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: marketplace-v1
  namespace: ${ISTIO_DEMO_NS}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: marketplace
        version: v1
        type: api-server
    spec:
      containers:
      - name: marketplace
        image: ${IMG_URL}:${ISTIO_DEMO_VERSION}
        imagePullPolicy: Always
        env:
        - name: SERVICE
          value: marketplace
        - name: APP_VERSION
          value: v1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: marketplace
  namespace: ${ISTIO_DEMO_NS}
  labels:
    app: marketplace
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: marketplace
---
