apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shipper-v1
  namespace: ${ISTIO_DEMO_NS}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shipper
        version: v1
        type: api-server
    spec:
      containers:
      - name: shipper
        image: ${IMG_URL}:${ISTIO_DEMO_VERSION}
        imagePullPolicy: Always
        env:
        - name: SERVICE
          value: shipper_v1
        - name: APP_VERSION
          value: v1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shipper-v2
  namespace: ${ISTIO_DEMO_NS}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shipper
        version: v2
        type: api-server
    spec:
      containers:
      - name: shipper
        image: ${IMG_URL}:${ISTIO_DEMO_VERSION}
        imagePullPolicy: Always
        env:
        - name: SERVICE
          value: shipper_v2
        - name: APP_VERSION
          value: v2
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shipper
  namespace: ${ISTIO_DEMO_NS}
  labels:
    app: shipper
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: shipper
---
