apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: users-v1
  namespace: ${ISTIO_DEMO_NS}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
        version: v1
        type: api-server
    spec:
      containers:
      - name: users
        image: ${IMG_URL}:${ISTIO_DEMO_VERSION}
        imagePullPolicy: Always
        env:
        - name: SERVICE
          value: users
        - name: APP_VERSION
          value: v1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: ${ISTIO_DEMO_NS}
  labels:
    app: users
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: users
---
